name: CI
run-name: ${{ github.workflow }} - ${{ github.event_name }} - ${{ github.ref }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      build-frontend-shared: ${{ steps.build-frontend-shared.outputs.artifact-path }}
      build-backend-shared: ${{ steps.build-backend-shared.outputs.artifact-path }}
      build-shared: ${{ steps.build-shared.outputs.artifact-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Clean build artifacts
        run: npm run clean

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Type check code
        run: npm run type-check

      - name: Build code
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload Test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: |
            packages/frontend/coverage
            packages/backend/coverage

      - name: Upload build artefact for frontend
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-frontend-shared
          path: packages/frontend/dist

      - name: Upload build artefact for backend
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-backend-shared
          path: packages/backend/dist

      - name: Upload build artefact for shared
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-shared
          path: packages/shared/dist
